import type { Metadata } from "next"
import type { CSSProperties } from "react"
import { getFontVariableClasses } from "@/app/fonts"
import { getSiteThemeFonts } from "@/lib/theme/get-site-theme"
import { resolveThemeFonts, type ThemeFontVariables } from "@/lib/theme/fonts"
import "./globals.css"

type ThemeStyle = CSSProperties & ThemeFontVariables

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const themeFonts = await getSiteThemeFonts()
    const resolvedFonts = resolveThemeFonts(themeFonts)
    const fontClasses = getFontVariableClasses(resolvedFonts.fontNames)

    return (
        <html lang="en" className={fontClasses} style={resolvedFonts.variables as ThemeStyle}>
            <body className="font-body antialiased">{children}</body>
        </html>
    )
}
